INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getCountOfArticles','select count(0) as countOfArticles from tblarticles where pubName=\'request:pubName\'','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getCountOfArticlesInMonth','select count(0) as countOfArticles from tblarticles where tblarticles.pubName=\'request:pubName\' \r\nand DATE_FORMAT(pubDate, \'%Y\')=request:year\r\nand DATE_FORMAT(pubDate, \'%m\')=request:month','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getCountOfArticlesInSectionRoot','select count(0) as countOfArticles from tblarticles,tblsections where tblarticles.pubName=\'request:pubName\' and tblsections.pubName=tblarticles.pubName and tblsections.section=tblarticles.section and (tblsections.sectionName like \'request:sectionName/%\' or tblsections.sectionName=\'request:sectionName\')','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getCountOfArticlesInState','select count(0) as countOfArticles from tblarticles where pubName=\'request:pubName\' and workflow_state=request:workflow_state','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getFirstMonth','select DATE_FORMAT(pubDate, \'%Y\') as pubYear, DATE_FORMAT(pubDate, \'%m\') as pubMonth from tblarticles where tblarticles.pubName=\'request:pubName\'  order by pubDate limit 1','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getLastMonth','select DATE_FORMAT(pubDate, \'%Y\') as pubYear, DATE_FORMAT(pubDate, \'%m\') as pubMonth from tblarticles where tblarticles.pubName=\'request:pubName\'  order by pubDate desc limit 1','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('activity_getRootSections','select section, sectionName, sectionDesc from tblsections where pubName=\'request:pubName\' and subMapOf=0 order by rank','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getAllArticles','SELECT * FROM tblarticleorder o, tblarticles a, tblsections s WHERE s.mappingCode=o.mappingCode AND a.itemID=o.itemID AND o.pubName=\'request:publication\' AND a.workflow_state=2 AND disableIndex=0 ORDER BY a.updateDate DESC','2005-08-30 13:05:00','2005-08-30 13:05:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getAllSections','select *, left(sectionDesc, 50) as sectionDesc50 from tblsections where pubName=\'request:publication\' order by sectionDesc','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getAllSubSectionsParam','SELECT S2.* FROM tblsections, tblsections S2 WHERE tblsections.mappingCode = S2.subMapOf AND tblsections.pubName = \'request:publication\' AND tblsections.sectionName = \'param:name\' and S2.displayOnIndex=1 order by rank','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getArticles','SELECT DISTINCT AP.itemID, AP.shortTime, AP.dayOfWeek, AP.virtualFolder, AP.pubYear, AP.pubMonth, AP.pubDay, AP.dateFolder, AP.pubDateLong, AP.articleLeadIn, AP.sigImage, AP.sigImageCaption, AP.listImage, AP.listImageCaption,    AP.articleImage, AP.articleImageCaption, AP.relatedLinksCount, AP.sigDir, AP.pubDesc, AP.orderingRank, AP.commentCount, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle FROM tblarticleorder t, tblarticles a, tblarticlepreload AP WHERE t.pubName=\'request:publication\' and t.section=\'request:name\' and a.itemID = t.itemId and A.workflow_state=2 and A.itemID = AP.itemID ','2005-01-17 16:50:46','2005-01-17 16:50:46',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getFirstSections','select * from tblsections where pubName=\'request:publication\' and subMapOf=\'0\' order by sectionDesc','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getHighMenu','select * from tblsections where pubname=\'request:publication\' and submapof=0 and displayOnIndex=1 order by rank','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getIdParentSection','select','2005-02-02 12:56:16','2005-02-02 12:56:16',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getLastArticles','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName,A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank,  		         A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, S.sectionDesc as sectionDesc, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.pubName = \'request:publication\' AND disableIndex = 0 order by  pubDate desc, orderingRank LIMIT 10','2005-01-17 16:50:46','2005-01-17 16:50:46',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getNews','select a.headline, a.fileName, a.headline2, a.lead, DATE_FORMAT(a.pubDate,\'%W, %M %D, %Y \') dateEn, DATE_FORMAT(a.pubDate,\'%x %c %a %W, %M %D, %Y \') dateFr, s.sectionName, a.body from tblarticles a, tblsections s, tblarticleorder ao \r\nwhere (s.mappingCode=\'param:mappingCode\' or s.subMapOf=\'param:mappingCode\') and a.itemID=ao.itemID and ao.mappingCode=s.mappingCode and a.disableArticle=0 and a.disableIndex=0 and a.workflow_state=2 order by a.pubRank, a.pubDate desc limit 0,param:limit','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getParentSection','select s.pubName, s.rank, s.section, s.sectionName, s.sectionDesc, s.image as image, s.sigDir, p.javaScript as publicationJavaScript, s.javaScript as sectionJavaScript, s.include as include, s.promo as promo, s.mappingCode, s.subMapOf, s.displayOnIndex FROM tblsections as s, tblsections as s1, tblpublications as p WHERE s.mappingCode = s1.subMapOf and s1.pubName = p.pubName and p.pubName = \'request:publication\' and s1.sectionName = \'request:name\' ','2005-01-27 15:35:59','2005-01-27 15:35:59',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getSearchArticles','SELECT distinct\r\nap.pubSectionDesc as sectionDesc,\r\na.headline as headline,\r\na.headline2,\r\na.lead,\r\na.fileName,\r\nCONCAT(pubDay, \'/\', pubMonth, \'/\', pubYear)  as datePub,\r\nCONCAT(pubYear, pubMonth, pubDay)  as datePub2,\r\nCONCAT(ap.virtualFolder, \'/\', a.fileName, \'.htm\') as linkArticle\r\nfrom\r\ntblarticlepreload ap, tblarticles a\r\nWHERE\r\na.itemID=ap.itemID\r\nand a.workflow_state=2\r\nand\r\n  (a.body like \'%request:searchstring%\'  OR a.headline like \'%request:searchstring%\'  OR a.headline2 like \'%request:searchstring%\')\r\nAND a.pubName=\'request:publication\'\r\norder by datePub2 desc','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getSearchSections','SELECT\r\n DISTINCT s.sectionDesc,\r\n s.sectionName,\r\n CONCAT(DATE_FORMAT(sectionUpdateDate, \'%d\'), \'/\', DATE_FORMAT(sectionUpdateDate, \'%m\'), \'/20\', DATE_FORMAT(sectionUpdateDate, \'%y\')) AS datePub,\r\n CONCAT(\'20\', DATE_FORMAT(sectionUpdateDate, \'%y\'), DATE_FORMAT(sectionUpdateDate, \'%m\'), DATE_FORMAT(sectionUpdateDate, \'%d\')) AS datePub2,\r\n s.url AS linkArticle,\r\n s.promo\r\nFROM\r\n tblsections s\r\nWHERE\r\n (s.include LIKE \'%request:searchstring%\' OR s.promo LIKE \'%request:searchstring%\' OR s.sectionDesc LIKE \'%request:searchstring%\')\r\nAND\r\n s.pubName = \'request:publication\'\r\nORDER BY\r\n datePub2 DESC','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getSection','SELECT DISTINCT A.body , AP.itemID, AP.shortTime, AP.dayOfWeek, AP.virtualFolder, AP.pubYear, AP.pubMonth, AP.pubDay, AP.dateFolder, AP.pubDateLong, AP.articleLeadIn, AP.sigImage, AP.sigImageCaption, AP.listImage, AP.listImageCaption,    AP.articleImage, AP.articleImageCaption, AP.relatedLinksCount, AP.sigDir, AP.pubDesc, AP.orderingRank, AP.commentCount, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle FROM tblarticleorder t, tblsections ts, tblarticles a, tblarticlepreload ap WHERE t.pubName=\'request:publication\' AND ts.sectionName=\'request:name\' AND t.section = ts.section AND ts.pubName= t.pubName AND a.itemID = t.itemID AND ap.itemID = a.itemID and A.workflow_state=2','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_getSections','select * from tblsections where pubName=\'param:pubName\' and displayOnIndex=1 order by rank','2005-08-23 17:00:00','2008-01-23 13:30:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('adt_get_niveau-1','select * from tblsections where pubName=\'request:publication\' and sectionName=\'request:section\'','2005-01-18 14:27:45','2005-01-18 14:27:45',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getAllAllowedSections','select S.* from tblsections as S, tblpermusersection AS PUS where PUS.mappingCode=S.mappingCode and PUS.manager=1 AND S.pubName=\'request:publication\' AND PUS.userID=user:userID','2003-05-28 00:00:00','2005-08-29 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getAllSections','select * from tblsections where pubName=\'request:publication\' ','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getAllSubSections','SELECT S2.* FROM tblsections, tblsections S2 WHERE tblsections.mappingCode = S2.subMapOf AND tblsections.pubName = \'request:publication\' AND tblsections.sectionName = \'request:name\' order by rank','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticle','SELECT DISTINCT A.body , AP.itemID, AP.shortTime, AP.dayOfWeek, AP.virtualFolder, AP.pubYear, AP.pubMonth, AP.pubDay, AP.dateFolder, AP.pubDateLong, AP.articleLeadIn, AP.sigImage, AP.sigImageCaption, AP.listImage, AP.listImageCaption,    AP.articleImage, AP.articleImageCaption, AP.relatedLinksCount, AP.sigDir, AP.pubDesc, AP.orderingRank, AP.commentCount, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle FROM tblarticleorder t, tblsections ts, tblarticles a, tblarticlepreload ap WHERE t.pubName=\'request:publication\' AND ts.sectionName=\'request:name\' AND t.section = ts.section AND ts.pubName= t.pubName AND a.itemID = t.itemID AND ap.itemID = a.itemID and A.workflow_state=2 AND A.fileName = \'request:fileName\'','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticlefromid','select AP.*, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle  FROM tblarticlepreload AS AP, tblarticles AS A, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.itemID = \'request:file_name\' AND disableArticle = 0 AND A.section=S.section order by orderingRank, pubDate desc','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticleTemp','SELECT tblarticles.*,DATE_FORMAT(tblarticles.pubDate,\'%e\') as pubDay, concat(DATE_FORMAT(tblarticles.pubDate,\'%Y\'),\'/\', DATE_FORMAT(tblarticles.pubDate,\'%c\'),\'/\',DATE_FORMAT(tblarticles.pubDate,\'%e\')) as dateFolder,DATE_FORMAT(tblarticles.pubDate,\'%c\') as pubMonth,DATE_FORMAT(tblarticles.pubDate,\'%Y\')\r\n as pubYear ,tblsections.* , tblmultimedia.itemName as articleImage, tblmultimedia.caption as caption,tblmultimedia.rank as rank FROM tblarticles left join tblsections on tblsections.pubName=tblarticles.pubName and tblsections.section=tblarticles.section left join tblmultimedia on tblmultimedia.ItemID=tblarticles.ItemID and tblmultimedia.type=\'articleImage\' WHERE tblarticles.ItemID=\'request:ITEMID\'','2003-05-28 00:00:00','2003-05-28 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticleType','select * from tblarticletypes where articleTypeID=\'request:articleTypeID\' ','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticleTypeByID','select * from tblarticletypes where articleTypeID = \'request:articleTypeID\'','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getArticleTypes','select * from tblarticletypes where pubName=\'request:pubName\' ','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getColumnistArchive','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S, tblarticleorder AS O WHERE AT.articleTypeName = \'request:fileName\' AND S.pubName = \'request:publication\' AND O.mappingCode = S.mappingCode AND O.itemID = AP.itemID AND A.itemID = AP.itemID AND disableIndex = 0 order by orderingRank, pubDate desc','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getColumnistGlossary','select * from tblarticletypes where pubName = \'request:publication\' and  articleTypeName = \'request:fileName\'','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getDefaultSection','select * from tblpublications','2000-12-20 16:02:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getGroupMembers','select * from tblpermusergroup, tblpermusers where groupId=\'getGroupMembers:groupID\' and tblpermusers.userID = tblpermusergroup.userID','2003-01-03 00:00:00','2003-01-03 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getGroupTypeMembers','select * from tblpermgroups where groupType=\'getGroupTypeMembers:groupTypeID\'','2003-01-03 00:00:00','2003-01-03 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getMonthDays','SELECT monthDayID, monthNameShort, monthID, dayNameShort,  dayName, dayID, numberDayOfMonth FROM tblmonthday','2000-12-20 16:27:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getNavigationByUserID','select distinct P.pubID, P.pubDesc, S.mappingCode, S.subMapOf, S.sectionDesc, O.itemID, A.fileName, PR.fullLink from tblpermusergroup AS PUG, tblpermgrouppublication AS PGP, tblpublications AS P, tblsections AS S, tblarticleorder AS O, tblarticlepreload AS PR, tblarticles AS A where PUG.userId = \'user:userID\'  and PUG.groupID = PGP.groupID and PGP.pubID = P.pubID and P.pubName = S.pubName and S.mappingCode = O.mappingCode and O.itemID = PR.itemID and A.itemID = PR.itemID order by pubID, mappingCode, subMapOf, itemID','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getOtherMultimedia','SELECT * from tblmultimedia where itemID = \'getArticle:itemID\' and type=\'other\' order by rank','2003-05-28 00:00:00','2003-05-28 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getOtherMultimediaFromId','SELECT * from tblmultimedia where itemID = \'getArticlefromid:itemID\' and type=\'other\' order by rank','2003-05-28 00:00:00','2003-05-28 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getPublications','SELECT publication, pubName, pubDesc, tagLine, homePage, icon, iconWidth,  iconHeight, javaScript, pubID, rolloverTime, hostName, defaultSection,  defaultSectionWithDate FROM tblpublications ORDER BY publication','2000-12-20 16:23:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getRelatedLinks','SELECT link, text from tblrelatedlinks where itemID = \'getArticle:itemID\' order by rank','2000-04-21 09:58:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getRelatedLinksTemp','SELECT link, text from tblrelatedlinks where itemID = \'getArticleTemp:itemID\' order by rank','2000-04-21 09:58:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getSearch','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.pubName = \'request:publication\' AND A.body LIKE \'%request:search%\' AND disableIndex = 0 order by orderingRank, pubDate desc','2003-05-14 00:00:00','2003-05-14 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getSection','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S,tblarticleorder AS O WHERE S.sectionName = \'request:name\' AND S.pubName = \'request:publication\' AND O.mappingCode = S.mappingCode AND O.pubDate = \'request:date\' AND O.itemID = AP.itemID AND A.itemID = AP.itemID AND disableIndex = 0 order by orderingRank, pubDate desc','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getSectionListArticles','select * from tblarticles where section=\'request:section\' and pubName = \'request:publication\'','0000-00-00 00:00:00','0000-00-00 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getSectionNoDate','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.pubName = \'request:publication\' AND AP.sectionName = \'request:name\' AND disableIndex = 0 and A.workflow_state=2 order by orderingRank, pubDate desc','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('getSectionTempNoDate','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.pubName = \'request:publication\' AND AP.sectionName = \'request:name\' AND disableIndex = 0 order by orderingRank, pubDate desc','0000-00-00 00:00:00','2002-08-13 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('PublicationGlossary','select tblpublications.* from tblpublications where tblpublications.pubName = \'request:publication\'','2000-04-19 16:25:00','2002-08-13 00:00:00',1);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('searchSection','select AP.*, AT.*, docID, A.fileName, versionNum, A.pubName, A.pubDate, A.section, A.headline,A.headline2, A.lead, A.webLead, A.dateline, A.keywords, A.pubRank, A.pubData, A.byline, A.bycredit, A.updateDate, A.docType, A.disableArticle, A.disableIndex, A.approved, A.leadIn, S.include as sectionInclude, S.promo as sectionPromo, CONCAT(AP.virtualFolder, \'/\', A.fileName) as linkArticle, A.body, A.dateline FROM tblarticlepreload AS AP, tblarticles AS A LEFT JOIN tblarticletypes AS AT ON A.articleTypeID=AT.articleTypeID, tblsections AS S WHERE A.itemID = AP.itemID AND AP.mappingCode = S.mappingCode AND A.pubName = \'request:publication\' AND A.section = \'request:section\' AND A.body LIKE \'%request:search%\' AND disableIndex = 0 order by orderingRank, pubDate desc','2003-05-14 00:00:00','2003-05-14 00:00:00',0);
INSERT INTO `tblpackagetags` (`tag_name`,`tag_value`,`create_date`,`modified_date`,`returnError`) VALUES 
  ('SectionGlossary','select s.keywords, s.pubName, s.rank, s.section, s.sectionName, s.sectionDesc, s.image as image, s.sigDir, p.javaScript as publicationJavaScript, s.javaScript as sectionJavaScript, s.include as include, s.promo as promo, s.mappingCode, s.subMapOf, s.displayOnIndex FROM tblsections as s, tblpublications as p WHERE s.pubName = p.pubName and p.pubName = \'request:publication\' and s.sectionName = \'request:name\'','2000-04-19 13:51:00','2002-08-13 00:00:00',0);



